# Site settings
title: Where I can be Wyzish 
email: your-email@domain.com
description: "Jwrobes is wyzish.  Only kind of wyz."
baseurl: ""
url: "http://wyzish.com"
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
